SHOW COLUMNS FROM user;
DESCRIBE user;
ALTER TABLE user ADD COLUMN email VARCHAR(150);
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
SELECT * FROM users;
